fourth_project/basic_app/urls.py
from django.urls import path
from . import views

# Template Tagging
app_name = "basic_app"

urlpatterns = [
    path("", views.index, name="index"),
    path("other/", views.other, name="other"),
    path("relative/", views.relative, name="relative"),
]

fourth_project/fourth_project/urls.py
from django.contrib import admin
from django.urls import path, include
from basic_app import views

urlpatterns = [
    path("", views.index),
    path("admin/", admin.site.urls),
    path("basic_app/", include("basic_app.urls")),
]

fourth_project/basic_app/views.py
from django.shortcuts import render


# Create your views here.
def index(request):
    context_dict = {"text": "hello world", "number": 100}
    return render(request, "basic_app/index.html", context_dict)


def other(request):
    return render(request, "basic_app/other.html")


def relative(request):
    return render(request, "basic_app/relative_url_templates.html")

fourth_project/templates/basic_app/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
</head>
<body>
<nav class="navbar navbar-default navbar-static-top">
    <div class="container">
        <ul class="nav navbar-nav">
            <li><a class="navbar-brand" href="{% url 'basic_app:index' %}">BRAND</a></li>
            <li><a class="navbar-link" href="{% url 'admin:index' %}">Admin</a></li>
            <li><a class="navbar-link" href="{% url 'basic_app:other' %}">Other</a></li>
        </ul>
    </div>
</nav>
<div class="container">
    {% block body_block %}
    <!-- Anything outside of this will be inherited if you extend!-->
    {% endblock %}
</div>
</body>
</html>

fourth_project/templates/basic_app/index.html
<!doctype html>
{% extends "basic_app/base.html" %}
{% block body_block %}
<h1>Welcome to index</h1>
<!--<h1>This is index.html page showing!</h1>-->
<h1>{{ text|cut:'hello' }}</h1>
<h1>{{ number|add:99 }}</h1>
{% endblock %}

fourth_project/templates/basic_app/other.html
<!doctype html>
{% extends "basic_app/base.html" %}
{% block body_block %}
<h1>Welcome to other</h1>
<h2>This is an example of template inheritance!</h2>
{% endblock %}

fourth_project/templates/basic_app/relative_url_templates.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
<h1>Welcome to relative URL Templates</h1>
<a href="{% url 'basic_app:other' %}">The Other Page</a>
<a href="{% url 'admin:index' %}">Link to Admin</a>
<a href="{% url 'basic_app:index' %}">Link to Index</a>
</body>
</html>